'use client';
import { useEffect, useState } from 'react';
import { Alert, Button, Dialog, Field, FileUpload, ImageCropper, Input, Select, Switch, Textarea } from '@foodconnect/ui/components';
import { saveMenuItem } from '@foodconnect/shared-utils';
import type { Currency, MenuItem } from '@foodconnect/shared-types';
const CATEGORIES = ['Main', 'Side', 'Drink', 'Dessert', 'Combo', 'Snack']; const CURRENCIES: Currency[] = ['NGN', 'USD'];
interface FormState { name: string; description: string; category: string; price: string; currency: Currency; bulkCapable: boolean; }
const emptyForm: FormState = { name: '', description: '', category: CATEGORIES[0], price: '', currency: 'NGN', bulkCapable: false };
export interface MenuItemDialogProps { open: boolean; onClose: () => void; sellerId: string; existingItem?: MenuItem | null; initialPhotoFile?: File | null; onSaved: () => void; }
export function MenuItemDialog({ open, onClose, sellerId, existingItem, initialPhotoFile, onSaved }: MenuItemDialogProps) {
  const [form, setForm] = useState<FormState>(emptyForm); const [rawFile, setRawFile] = useState<File | null>(null); const [croppedFile, setCroppedFile] = useState<File | null>(null); const [previewUrl, setPreviewUrl] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!open) return; if (existingItem) { setForm({ name: existingItem.name, description: existingItem.description, category: existingItem.category, price: String(existingItem.price), currency: existingItem.currency, bulkCapable: existingItem.bulkCapable }); setPreviewUrl(existingItem.photoUrl ?? null); } else { setForm(emptyForm); setPreviewUrl(initialPhotoFile ? URL.createObjectURL(initialPhotoFile) : null); } setRawFile(null); setCroppedFile(initialPhotoFile ?? null); setError(null); }, [open, existingItem, initialPhotoFile]);
  function updateField<K extends keyof FormState>(key: K, value: FormState[K]) { setForm(current => ({ ...current, [key]: value })); }
  function handleCropped(file: File) { setCroppedFile(file); setPreviewUrl(URL.createObjectURL(file)); setRawFile(null); }
  async function handleSubmit() { setError(null); if (!form.name.trim()) { setError('Item name is required.'); return; } const price = Number(form.price); if (!Number.isFinite(price) || price <= 0) { setError('Enter a valid price greater than zero.'); return; } setSaving(true); try { await saveMenuItem(sellerId, { ...form, name: form.name.trim(), description: form.description.trim(), price, photoFile: croppedFile }, existingItem ?? undefined); onSaved(); } catch (err) { setError(err instanceof Error ? err.message : 'Could not save this menu item. Please try again.'); } finally { setSaving(false); } }
  return <Dialog open={open} onClose={onClose} title={existingItem ? 'Edit menu item' : 'Add menu item'} description="Photos, pricing, and descriptions are visible to customers immediately." size="lg"><div className="field-grid"><Field label="Photo" htmlFor="itemPhoto" hint="Square or landscape photos work best.">{rawFile ? <ImageCropper key={rawFile.name + rawFile.lastModified} file={rawFile} onCancel={() => setRawFile(null)} onCropped={handleCropped} /> : <>{previewUrl && <div className="menu-photo-preview"><img src={previewUrl} alt="Menu item preview" /></div>}<FileUpload label={previewUrl ? 'Replace photo' : 'Upload a photo'} hint="JPG or PNG up to 10MB" accept="image/*" maxSizeMB={10} onFileSelected={file => file && setRawFile(file)} /></>}</Field><Field label="Item name" htmlFor="itemName" required><Input id="itemName" value={form.name} onChange={event => updateField('name', event.target.value)} placeholder="e.g. Jollof rice with grilled chicken" /></Field><Field label="Category" htmlFor="itemCategory" required><Select id="itemCategory" value={form.category} onChange={event => updateField('category', event.target.value)}>{CATEGORIES.map(category => <option key={category}>{category}</option>)}</Select></Field><div className="field-grid-split"><Field label="Price" htmlFor="itemPrice" required><Input id="itemPrice" type="number" min={0} step="0.01" value={form.price} onChange={event => updateField('price', event.target.value)} placeholder="3500" /></Field><Field label="Currency" htmlFor="itemCurrency" required><Select id="itemCurrency" value={form.currency} onChange={event => updateField('currency', event.target.value as Currency)}>{CURRENCIES.map(currency => <option key={currency}>{currency}</option>)}</Select></Field></div><Field label="Description" htmlFor="itemDescription" hint="Shown to customers on the item card."><Textarea id="itemDescription" rows={3} value={form.description} onChange={event => updateField('description', event.target.value)} placeholder="Smoky jollof rice with grilled chicken and fried plantain" /></Field><label className="switch-row"><Switch checked={form.bulkCapable} onCheckedChange={value => updateField('bulkCapable', value)} /><span>Available for B2B bulk orders</span></label></div>{error && <Alert tone="error" title="Could not save item">{error}</Alert>}<div className="dialog-actions"><Button variant="ghost" onClick={onClose} disabled={saving}>Cancel</Button><Button onClick={handleSubmit} disabled={saving}>{saving ? 'Saving...' : existingItem ? 'Save changes' : 'Add item'}</Button></div></Dialog>;
}